# SPDX-FileCopyrightText: 2026 MesTTo
# SPDX-License-Identifier: Apache-2.0

name = "leatta"
defaultTargets = ["Docs", "docs"]

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "3bdedf29bada13d8103e6c979001c51dcee210c8"

[[lean_lib]]
name = "Docs"

[[lean_exe]]
name = "docs"
root = "Main"
